name: flutter_application
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.15
  image_cropper: ^5.0.0
  animations: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  introduction_screen: ^3.1.11
  shared_preferences: ^2.2.1
  uuid: ^4.1.0
  matrix_gesture_detector:
    git:
      url: https://github.com/besttechguru/matrix_gesture_detector.git
  flutter_overlay_window: ^0.4.3
  screenshot: ^2.1.0
  flutter_keyboard_visibility: ^5.4.1
  collection: ^1.18.0
  permission_handler: ^11.1.0
  lint: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_layout_grid: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  null_safety_percentage: ^2.1.1
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Kalam-Bold
      fonts:
        - asset: lib\assets\fonts\Kalam\Kalam-Bold.ttf
    - family: Kalam-Light
      fonts:
        - asset: lib\assets\fonts\Kalam\Kalam-Light.ttf
    - family: Kalam-Regular
      fonts:
        - asset: lib\assets\fonts\Kalam\Kalam-Regular.ttf
